urls.py


from django.urls import path,re_path
from .import views 
from django.views.generic import ListView
app_name="ecom"
urlpatterns=[
  path('retry-payment/<order_id>', views.retry_payment, name='retry_payment'),
  path('process-payment/', views.payment_process, name='payment_process'),


  #path('', views.show_cat, name='show_cat',),
  path('accounts/profile/', views.profile, name='profile',),
  path('search/', views.search, name='search',),
  path('all/<category_slug>/', views.all_products, name='all_products',),
  path('subcat/<sub_category_slug>/', views.all_products, name='all_products',),
  path('all/<query>/', views.all_products, name='all_products',),
  path('all/', views.all_products, name='all_products',),
  path('delete-unpaid/', views.delete_unpaid_order, name='delete_unpaid_order',),
  path('rate_order/<rated_id>/',views.rate,name='rate'),
  path('', views.index, name='index'),

  path('add_wish/<id>',views.add_wish,name='add_wish'),
  path('delete-order/<id>',views.delete_order,name='delete_order'),

  path('remove_wish/<id>',views.remove_wish,name='remove_wish'),
  path('create_order/',views.create_order,name='create_order'),
  path('product/<id>/<slug>/',views.post_detail,name='post_detail'),
  path('one_order/<post_id>/<color>/<extra>/',views.one_order,name='one_order'),
  path('one_order/<post_id>/',views.one_orders,name='one_orders'),

  path('delete-one_order/<order_id>',views.remove_order,name='remove_order'),


    
 ]

models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor.fields import RichTextField
from taggit.managers import TaggableManager
from django.db.models.signals import post_delete,post_save
from django.dispatch import receiver
import os 
from django.utils.safestring import mark_safe 

class SubCategory(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50,unique=True)
    
    
    class Meta:
        ordering=('name',)
        verbose_name ='Sub category'
        verbose_name_plural='Sub categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('ecom:list_category',args=[self.slug])
class Category(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50,unique=True)
    sub_category = models.ManyToManyField(SubCategory)
    class Meta:
        ordering=('name',)
        verbose_name ='category'
        verbose_name_plural='categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('ecom:list_category',args=[self.slug])





class Post(models.Model):
    status_choices=(
         ('draft','Draft'),('published','Published')
        )
    title=models.CharField(max_length=20)
    slug=models.SlugField(max_length=200,unique_for_date='publish',)
    category = models.ManyToManyField(Category)
    subo_category = models.ManyToManyField(SubCategory)
    discription1=RichTextField()
    discription2=RichTextField()
    out_of_stock=models.BooleanField(default=False)
    price_before=models.DecimalField( max_digits=5, decimal_places=2, blank=True, null=True)
    price=models.DecimalField( max_digits=5, decimal_places=2)
    author=models.ForeignKey(User,related_name='blog_posts', on_delete=models.CASCADE)
    publish=models.DateTimeField(default=timezone.now)
    created=models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)
    status = models.CharField(max_length=10,choices=status_choices,default='draft')
    photo=models.ImageField(upload_to='documents',blank=True)
    #tags = TaggableManager()



    class Meta:
        ordering=('-publish',)
        index_together = (('id', 'slug'),) 
        verbose_name_plural ='Items'
        verbose_name ='Items'
    def __str__(self):
        return self.title.replace(' ','-')





    def get_absolute_url(self):
        return reverse('ecom:post_detail', args=[self.id,self.slug])

@receiver(post_delete, sender=Post)
def photo_post_delete_handler(sender, **kwargs):
    photos = kwargs['instance']
    storage, path = photos.photo.storage, photos.photo.path
    storage.delete(path)



class Image(models.Model):
    image = models.ImageField(upload_to='documents')
    post = models.ForeignKey(Post,related_name='post_image',on_delete=models.CASCADE)
    active = models.BooleanField(default=True)

@receiver(post_delete, sender=Image)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False)

class Color(models.Model):
    color_choices=(
         ('red','Red'),('green','Green'),
         ('black','Black'),('yellow','Yellow'),

         ('blue','Blue'),('brown','Brown'),
         ('orange','Orange'),('white','White'),
         ('grey','Grey'),('pink','Pink'),

        )
    color = models.CharField(max_length=10,blank=True,null=True,choices=color_choices,default=None)
    post = models.ForeignKey(Post,related_name='post_color',on_delete=models.CASCADE)
    active = models.BooleanField(default=False)
    def __str__(self):
        return self.color

class TextChoice(models.Model):

    product_extra_choice = models.CharField(max_length=10,default=None)
    post = models.ForeignKey(Post,related_name='post_text',on_delete=models.CASCADE)
    active = models.BooleanField(default=False)
    def __str__(self):
        return self.product_extra_choice

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    zipcode = models.CharField(max_length=30, blank=True)   
    location = models.CharField(max_length=30, blank=True)
    name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    phone=models.CharField(max_length=30,null=True,blank=True)
    photo=models.ImageField(upload_to='documents/profile',blank=True,null=True ,default='/documents/profile/oneuser.jpg')
    wish=models.ManyToManyField(Post, related_name='wished' ,blank=True)

    def get_profile_picture(self):

        if self.photo:
            return photo_url
        else:
            return '/documents/profile/oneuser.jpg/'
    def __str__(self):
        return 'Profile: {}'.format(self.user)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()
   


@receiver(post_delete, sender=Profile)
def photo_post_delete_handler(sender, **kwargs):
    photo = kwargs['instance']
    storage, path = photo.photo.storage, photos.photo.path
    storage.delete(path)

@receiver(models.signals.pre_save, sender=Profile)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """
    Deletes old file from filesystem
    when corresponding `MediaFile` object is updated
    with new file.
    """
    if not instance.pk:
        return False

    try:
        old_file = sender.objects.get(pk=instance.pk).photo
    except sender.DoesNotExist:
        return False

    new_file = instance.photo
    if not old_file == new_file:
        if os.path.isfile(old_file.path):
            os.remove(old_file.path)

class Order(models.Model):
    profile = models.ForeignKey(Profile,default="", related_name='items', on_delete=models.CASCADE)
    order_time=models.DateTimeField(default=timezone.now)
    paid = models.BooleanField(default=False)

    shipping_address=RichTextField()

    class Meta:

        ordering = ('-order_time',)
    def __str__(self):
        return 'Order {}'.format(self.id)
    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all() )


class Ratings(models.Model):
    profile = models.ForeignKey(Profile, related_name='rate_profile',  on_delete=models.CASCADE)
    rate = models.PositiveIntegerField(default=0)
    feedback=models.CharField(max_length=300,null=True, blank=True)
    order=models.ForeignKey(Order, default="", on_delete=models.SET_NULL, null=True,)
    posti=models.ForeignKey(Post,related_name='ra_items',  on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return '{}'.format(self.id)

        
class OrderItems(models.Model):
    profile = models.ForeignKey(Profile, related_name='item', on_delete=models.CASCADE)
    rated=models.ForeignKey(Ratings,related_name='rate_items',   on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Post,default="",related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=3)
    order_time=models.DateTimeField(default=timezone.now)
    quantity = models.PositiveIntegerField(default=1)
    color=models.CharField(max_length=300,null=True, blank=True)
    extra=models.CharField(max_length=300,null=True, blank=True)

    order=models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)

    def __str__(self):
        return self.user
    def __str__(self):
        return '{}'.format(self.id)


    def get_cost(self):
        return self.price * self.quantity



templates/detail.html
{% extends "base.html" %}
{% load static %}
{% load mathfilters %}
{% load crispy_forms_tags %}
  {% block content%}

<link rel="stylesheet" href="{% static "css/detail.css" %}"> 

  <link href="https://www.jqueryscript.net/css/jquerysctipttop.css" rel="stylesheet" type="text/css">
  <script src="{% static "js/jquery.zoom.min.js" %}"></script>

<style type="text/css">
</style>

<div class=" container-fluid  mt-5 ">
	
  <div class="row ">

  <div class="col-md-5">
    
  <div style="margin: auto; padding-bottom: 0px!important; " class="mt-5 shows" >
    <img   id= "zog"  style="max-height: 350px;" src="{{post.photo.url}}" class="w-100 animated">
</div>

<div class="carousel-wrap sil  text-center">
    

  <div class="brand vb ps owl-carousel">

        {% for ph in image%}
            <div  class="item col"><img  src="{{ph.image.url }}"></div>
    

       {% endfor %}
  

    
  </div>

    </div>
    </div>


<div id="mnk"> </div>
 <style>
   #mnk select{
    display: block!important;
   }
 </style>
 <script type="text/javascript">


  
$(document).ready(function() {
var fsua= $('#faso').attr('action');



   var cold= $("#id_colors").val()
   //$('#id_color').val(cold)
   var colid= $("#id_extras").val()
  // $('#id_extra').val(colid)
   

    $("#id_colors").change(function(){
   var col= $(this).val()
   var colido= $("#id_extras").val()
   $('#id_color').val(col)
   $('#faso').attr('action','/one_order/'+post+'/'+col+'/'+colido+'/');
  });


    $("#id_extras").change(function(){
   var coli= $(this).val()
   var coldo= $("#id_colors").val()

   $('#id_extra').val(coli)
   $('#faso').attr('action','/one_order/'+post+'/'+coldo+'/'+coli+'/');
  });


var post= '{{post.id}}';
if (typeof cold === 'undefined') {
    $('#faso').attr('action','/one_order/'+post+'/');
}
else {
  $('#faso').attr('action','/one_order/'+post+'/'+cold+'/'+colid+'/');
}

if (typeof colid === 'undefined') {
  $('#id_extra').val('Not set');
    
}

});

 $(function() {
  var $select = $('#id_quantity');
  var pricon= "{{ post.price }}";

   //var new= item*producct_price;
  $select.on('change', function() {
       
    var value = parseInt($('#id_quantity').val());
    var item_price=parseInt(pricon);
    var newp= value * "{{ post.price }}";
     $('#total').text(newp+'$');


  });


});




</script>

<div  class=" mt-5  tex col-md-5 car"  >

  
<form action="{% url "cart:cart_add" post.id %}" id="fdd" method="POST">
 {% csrf_token %}

 {{ cart_product_form|crispy }}




 <div class="price"> Price per item <strong>{{ post.price|make_list|slice:'-3'|join:'' }}$</strong></div>

<div>Total <strong id="total"> </strong></div>

</form>
{% if color %}
<select class="bnv" id="id_colors">
{% for colore in color %}
  <option value="{{colore.color|capfirst}}">{{colore.color|capfirst}}</option>


{% endfor %}
</select>
{% endif %}

{% if extra_choice %}
<select class="bnv" id="id_extras">
{% for choice in extra_choice %}
  <option value="{{choice.product_extra_choice|capfirst}}">{{choice.product_extra_choice|capfirst}}</option>


{% endfor %}
</select>
{% endif %}
<hr>
{% if cart %}

<button  for="fdd" style="transform: skewX(-10deg);" type="submit" class="btn btn-warning  cart_on  shad  "><i class="fa fa-shopping-cart" style="font-size:24px; "></i> Add to Cart</button>
  {% for item in cart %}
                {% with prod=item.post %} 
                             {% if prod.id == post.id %}

  <button   onclick="event.preventDefault()" for="fdd" style="transform: skewX(-10deg);" type="submit" class="btn btn-warning  shad  "><i class="fas fa-check-circle" style="color: green; font-size:22px"></i> On Cart</button>
<style>
  
.cart_on{
  display: none;
}

</style>     

                                      {% endif %}
                           {% endwith %}
               {% endfor %}
      {% else %}
<button  for="fdd" style="transform: skewX(-10deg);" type="submit" class="btn btn-warning  cart_on  shad  "><i class="fa fa-shopping-cart" style="font-size:24px; "></i> Add to Cart</button>

  {% endif %}





<form style="display: inline-block;transform: skewX(-10deg);" id="faso{{forloop.counter}}" action=""  method="POST">

  {% csrf_token %}
  


  <button name="one_order"  style="margin:0rem 0rem 0rem 0rem;"  class="btn btn-warning  sub shad" ><i style="font-size: 20px;" class="fas fa-credit-card"></i> Buy just One </button>



      </form>


<style>


  .bn{display: none;}

.asteriskField{display: none;}
.control-label{font-weight: }</style>
<div class="text-center" style="font-weight: 600;color:white;border-color: white;box-shadow:10px 10px  20px #00000054;border-style: solid;background-color: black;">



  <div class="reduce" >

 {% if post.price_before > post.price %}
  <i >Was</i> <i style=" text-decoration: line-through ;color: red;" >  {{ post.price_before|make_list|slice:'-3'|join:''}}$</i>
{% endif %}

 




{% if post.price_before > post.price %}
<span class="s_span" >
 



    <i> <i >Save</i> {{ post.price_before|sub:post.price|make_list|slice:'-3'|join:'' }}$</i>
    </span>
{% endif %}

<span>
</div>


  	       <p class="text-center" style="font-size: 120%;"  > 


           {{post.discription1|safe}}</p>
                          </div>
          
             </div>
</div>

</div>

<div class=' test mt-5 ml-2' >
  
<div style=" position: relative;z-index: 55;top: 3px;" class="mnj">
  
<span class="btn  desc border " > Item description </span>
<span  class="btn   rev "  > Users feedbacks </span>


</div>
<style>
  .show-more-height{
    overflow: hidden;
    height: 250px;
  }
</style>
<div class="container-fluid">
 
  <div class="row ">
  <div  class="  col-12 cae ">

<div class=" tvu show-more-height">
  <p class="text-center">{{post.discription2|safe}}</p>
</div>
<button style=" background-color: #807e7e;; font-weight: 700;" class=' btn show-more mt-1'>Show More </button>
  </div>
  
  <script>
        $(".show-more").click(function () {
        if($(".tvu").hasClass("show-more-height")) {
            $(this).text("Show Less");
        } else {
            $(this).text("Show More");
        }

        $(".tvu").toggleClass("show-more-height");
    });
  </script>
  <!-- feedbacks of products begin --> 
  
<div class="container-fluid ratings " >







{% for rated in feedback.all %}

  {% if rated.rate > 0  %}
<style>
  .xero{
    display: none;
  }
</style>
<script type="text/javascript">
  $(document).ready(function($) {

//var nn= $('#rat'+'{{ rated.rate}}').attr('id');
$('#{{forloop.counter}}'+'rat'+'{{ rated.rate}}').children('span:lt({{rated.rate}})').addClass('checked');
    
 
  });

  </script>
<div  class="row fano animated ml-2 mt-2">

<script>


var url_on=$('#image_id'+'{{forloop.counter}}').attr('src');
console.log(url_on)
     $.get('{{rated.profile.photo.url}}')
    .done(function() { 
       
    }).fail(function() { 
        
  $('#image_id'+'{{forloop.counter}}').attr('src', '/static/img/unknown.png');

    })
</script>

  <img id="image_id{{forloop.counter}}" style="border-radius: 50%;height: 80px;width: 80px;"  src="{{rated.profile.photo.url}}" alt="">
<span> {{rated.profile.user}}   


<div style="font-weight: 900;" class="rate" val='{{ rated.rate}}' id="{{forloop.counter}}rat{{ rated.rate}}">{{rated.rate}}/5
  
  <span class="fa fa-star" data-value='1'></span>
  <span class="fa fa-star" data-value='2'></span>
  <span class="fa fa-star" data-value='3'></span>
  <span class="fa fa-star" data-value='4'></span>
  <span class="fa fa-star" data-value='5'></span>

</div>

<p style="font-size: 20px;">{{rated.feedback}}</p>

</span>


</div>


{% endif %}
{% endfor %}


{% for rated in feedback.all|slice:'1' %}

 {% if rated.rate == 0 or feedback == empty %}
  
<style>

</style>
<div class="container text-center xero">
  <div style="margin:35px;" class='text-center mt-3' > <strong style="font-size: 20px; color: black;background-color: white;padding: 8px;">No Feedbacks !</strong> </div>
</div>

{% endif %}

{% empty %}
<style>

</style>
<div class="container text-center xero">
  <div style="margin:35px;" class='text-center mt-3' > <strong style="font-size: 20px; color: black;background-color: white;padding: 8px;">No Feedbacks !</strong> </div>
</div>
{% endfor %}



</div>





</div>
</div>
</div>

  <!-- feedbacks of products begin --> 

  <!-- similar products begin -->	
  <div class="similar mt-2 vb ps text-center owl-carousel">

{%  for slid in similar_post%}
        <div class="up container text-center">

 <span style="position: absolute;z-index: 4;left: 0px;top: 40px;">
            

<form style="display: none;" id="rem{{slid.id}}" class="wish2 " method="POST" action="/remove_wish/{{slid.id}}">
                            {% csrf_token %}
                            <input type="hidden" name="supporttype" />
                            <button  class="remove1 animated shad btn " type="submit"><i style="color: red!important;" class="  fas fa-heart"></i></button> </form>
     

<form id="{{slid.id}}" class="wish" method="POST" action="">
                            {% csrf_token %}
                                  <input type="hidden" name="supporttype" />
                                <button class="add1 animated shad btn" type="submit"><i class="animated fas fa-heart"></i></button> </form>
                          

 {% if slid in request.user.profile.wish.all %}
 <script type="text/javascript">

  $(document).ready(function($) {

    var no= '{{slid.id}}'
  
    $("#"+no).attr('action','/remove_wish/'+ no);
    $("#rem"+no).css('display','block')
    $("#"+no).css('display','none')

  });

 
 </script>


{%else%}
 <script type="text/javascript">
      $(document).ready(function($) {

    var no= '{{slid.id}}'
  
$("#"+no).attr('action','/add_wish/'+ no)
    $("#rem"+no).css('display','none')
    $("#"+no).css('display','block')
    
  });
   
 </script>
 {%endif%}


<script type="text/javascript">
    $('.formos').click(function(e){

$('#carta').addClass('bounceIn')
setTimeout(function(){
$('#carta').removeClass('bounceIn')

}, 500);

      });



  $(document).ready(function($) {
       var no= '{{slid.id}}'
      $('#rem'+no).click(function(event){

         $('#'+no).toggle();
         $(this).hide();


               });
  
      $('#'+no).click(function(event){

         $('#rem'+no).toggle();
         $(this).hide();
         

      });
  });
   
 </script>



 </span>

<span style="position: absolute;z-index: 3;left: 0px;" >
  

<form action="{% url "cart:cart_add" slid.id %}" id="fddd{{slid.id}}" class=" slideo slideos{{slid.id}}" method="POST">

 {% csrf_token %}

 {{ cart_product_form|crispy }}




{% if cart %}


  {% for item in cart %}
                {%  with prod=item.post %} 
                             {% if prod.id == slid.id %}

  <button   onclick="event.preventDefault()" for="fddd{{slid.id}}" style="z-index: 9; position: absolute; " type="submit" class="btn btn-warning  shad {{prod.id}} {{slid.id}} "><i class="fas fa-check-circle" style="color: green; font-size:22px"></i> On Cart</button>
    
<script>

$(document).ready(function(){

  $('#fddd{{slid.id}}').attr('action','Not');
  var tv= $('#fddd{{slid.id}}').find('.add');
  tv.hide();

});

</script>


{%else%}




<button   style="position: absolute;" type="submit" class="btn btn-warning {{prod.id}} {{slid.id}} cart_ons  add shad  "><i class="fa fa-shopping-cart" style="font-size:24px; "></i> Add </button>
                                      {% endif %}
                              {% endwith %}
                 {% endfor %}
      {% else  %}
<button  style="" type="submit" class="btn btn-warning  cart_ons  shad  "><i class="fa fa-shopping-cart" style="font-size:24px; "></i> Add </button>

  {% endif %}

</form>


</span>

<a href="{{ slid.get_absolute_url }}">

   
            <div  class="item col"><img  src="{{slid.photo.url}}"></div>


<div class="mnos"><span style="font-size: 17px;">{{ slid.title|capfirst}}</span> -<span style="color:black;background-color: white;"><strong>-{{slid.price|make_list|slice:'-3'|join:''}}<span style="font-size: 17px;">$</span>-</strong></span>
   </div>
  </a>
      </div>   

{% endfor %}


  </div>


  <!-- similar products ends  --> 




</div>

	
</div>




 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css" />
  <link href= "{% static "css/owl.carousel.min.css" %}" rel="stylesheet">
  <link href= "{% static "css/owl.theme.default.min.css" %}" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.js"></script>
  <script src="{% static "js/owl.autoplay.js" %}"></script>
   <script src="{% static "js/detail.js" %}"></script>
 {% endblock %}
 </body>
 </html>

templates/pagination.html


<div class="container ">
 {% if post.has_other_pages %}
   

  <ul class="pagination justify-content-center ">
    {% if post.has_previous %}
      <li><a id="previo" class="page-link shad " href="?page={{ post.previous_page_number }}
        {%if request.GET.reduced%}&reduced={{request.GET.reduced}}{%endif%}{%if request.GET.high%}&high={{request.GET.high}}{%endif%}
        {%if request.GET.search%}&search={{request.GET.search}}{%endif%}
      {%if request.GET.number%}&number={{request.GET.number}}{%endif%}
        {%if request.GET.low%}&low={{request.GET.low}}{%endif%}
        {%if request.GET.mini%}&mini={{request.GET.mini}}{%endif%}
        {%if request.GET.maxi%}&maxi={{request.GET.maxi}}{%endif%}">❮</a></li>
    
    {% endif %}
    {% for i in post.paginator.page_range|slice:":5" %}
      {% if post.number == i %}
     
      <li   class="page-item active"><a class="page-link shad " href="">{{ i }}</a></li>
        
      {% else %}
        <li ><a  class="page-link numbe shad" href="?page={{i}}{%if request.GET.reduced%}&reduced={{request.GET.reduced}}{%endif%}
          {%if request.GET.high%}&high={{request.GET.high}}{%endif%}
          {%if request.GET.search%}&search={{request.GET.search}}{%endif%}
          {%if request.GET.low%}&low={{request.GET.low}}{%endif%}
{%if request.GET.number%}&number={{request.GET.number}}{%endif%}          
          {%if request.GET.mini%}&mini={{request.GET.mini}}{%endif%}
        {%if request.GET.maxi%}&maxi={{request.GET.maxi}}{%endif%}">{{ i }}</a></li>
      
      {% endif %}
    {% endfor %}
    {% if post.has_next %}
    {% if post.paginator.num_pages > 5 %}
    
{% for c in post.paginator.page_range|slice:'5:' %}
      {% if post.number == c %}
       
      <li   class="page-item active  "><a class="page-link numbe shad" href="">-{{ c }}-</a></li>


   {% endif %}
    {%endfor%}
   
<li><a class="page-link page-item active shad  " href="?page={{post.paginator.num_pages}}">❯{{ post.paginator.num_pages}}</a></li>
    


    {%endif%}
 
            
      <li><a id="next" class="page-link shad" href="?page={{ post.next_page_number }}{%if request.GET.reduced%}&reduced={{request.GET.reduced}}{%endif%}
        {%if request.GET.high%}&high={{request.GET.high}}{%endif%}
        {%if request.GET.search%}&search={{request.GET.search}}{%endif%}
{%if request.GET.number%}&number={{request.GET.number}}{%endif%}
        {%if request.GET.low%}&low={{request.GET.low}}{%endif%}
        {%if request.GET.mini%}&mini={{request.GET.mini}}{%endif%}
        {%if request.GET.maxi%}&maxi={{request.GET.maxi}}{%endif%}">❯</a></li>
    

  
        {% endif %}
    
  </ul>

{% endif %}
</div>
<script type="text/javascript">
  $(document).ready(function(){

if($('.numbe')){
 $('.numbe').each(function() {
   
 
var stris =$(this).attr('href');
var nes = stris.replace(/\s+/g, '');

$(this).attr('href',nes);

});
}


    if ($('#previo').attr('href')) {
var stri =$('#previo').attr('href');
var nei = stri.replace(/\s+/g, '');
//alert(ne)
$('#previo').attr('href',nei);
}
if ($('#next').attr('href')) {
var str =$('#next').attr('href');
var ne = str.replace(/\s+/g, '');
//alert(ne)
$('#next').attr('href',ne);

}
  });

</script>

<style >
.page-item:first-child .page-link {
    margin-left: 0;
   border-top-left-radius: 50%; 
   border-bottom-left-radius: .25rem;
}
.page-item:last-child .page-link {
     border-top-right-radius: 50%; 
    border-bottom-right-radius: .25rem;
}
.pagination li:hover{
  
transform: scale(1.1); /* Standard syntax */
  transition: all .5s;
}
.page-link{
  font-weight: bold;
}
.page-link:hover{
  color:black!important;
}
.pagination{
   
    margin:5px;


  }
li{
  padding: 3px;
}
.pagination a {
 color: #061421;
  padding:15px;  
  height: 50px;
  width:50px; 
  border-radius: 50%;
} 

.pagination a:hover:not(.active) {background-color: #DCDCDC}
@media  (max-width: 800px) {
    .pagination{

   padding: 0px 0px 0px 0px; 
}

 
.pagination a {
    background-color:#F0F8FF;
 padding:10px;

   
  
}

}
</style>
